"""Shared fixtures for hermes-base tests.

Integration tests (`pytest -m integration`) load wire-dev env from
`agents-runtime/.env.dev.local` (generated by `./scripts/wire-dev.sh env`).
Requires `./scripts/wire-dev.sh up` so Postgres/Redis port-forwards are active.
"""

from __future__ import annotations

import os
import uuid
from collections.abc import AsyncIterator
from pathlib import Path

import pytest

HERMES_ROOT = Path(__file__).resolve().parents[3]
AGENTS_RUNTIME_ROOT = (HERMES_ROOT / "../../works/agents-runtime").resolve()
KIND = "agent"


def _wire_dev_env_paths() -> list[Path]:
    explicit = os.environ.get("HERMES_WIRE_DEV_ENV")
    paths: list[Path] = []
    if explicit:
        paths.append(Path(explicit).expanduser())
    paths.extend(
        [
            AGENTS_RUNTIME_ROOT / ".env.dev.local",
            HERMES_ROOT / ".env.dev.local",
        ]
    )
    return paths


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    out: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :]
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] == '"':
            value = bytes(value[1:-1], "utf-8").decode("unicode_escape")
        out[key] = value
    return out


def _merged_wire_env() -> dict[str, str]:
    merged: dict[str, str] = {}
    for path in _wire_dev_env_paths():
        merged.update(_parse_env_file(path))
    merged.update(os.environ)
    return merged


def _normalize_dsn(dsn: str) -> str:
    return dsn.replace("postgresql+asyncpg://", "postgresql://")


def _wire_dev_dsn(env: dict[str, str] | None = None) -> str | None:
    merged = env or _merged_wire_env()
    dsn = merged.get("VFS_DSN") or merged.get("POSTGRES_DSN", "")
    if not dsn:
        return None
    return _normalize_dsn(dsn)


def _wire_dev_session_dsn(env: dict[str, str] | None = None) -> str | None:
    merged = env or _merged_wire_env()
    dsn = (
        merged.get("HERMES_SESSION_DSN")
        or merged.get("VFS_DSN")
        or merged.get("POSTGRES_DSN", "")
    )
    if not dsn:
        return None
    return _normalize_dsn(dsn)


@pytest.fixture(scope="session")
def wire_dev_env() -> dict[str, str]:
    """Merge wire-dev `.env.dev.local` into os.environ for the test session."""
    loaded: dict[str, str] = {}
    for path in _wire_dev_env_paths():
        loaded.update(_parse_env_file(path))
    if loaded:
        os.environ.update(loaded)
    return loaded


@pytest.fixture()
async def vfs_pool(wire_dev_env: dict[str, str]) -> AsyncIterator[object]:
    from runtime_common.vfs.store import create_asyncpg_pool

    dsn = _wire_dev_dsn(wire_dev_env)
    if not dsn:
        pytest.skip(
            "VFS_DSN unset — run: (agents-runtime) ./scripts/wire-dev.sh up && "
            "./scripts/wire-dev.sh env"
        )
    try:
        pool = await create_asyncpg_pool(dsn, min_size=1, max_size=4)
        async with pool.acquire() as conn:
            await conn.fetchval("SELECT 1")
    except OSError as exc:
        pytest.skip(f"wire-dev Postgres unreachable ({dsn}): {exc}")
    except Exception as exc:  # noqa: BLE001 — skip when cluster DB not wired
        pytest.skip(f"wire-dev Postgres connect failed: {exc}")

    yield pool
    await pool.close()


@pytest.fixture()
async def vfs_store(vfs_pool: object):
    from runtime_common.vfs.store import AsyncpgAgentVfsStore

    return AsyncpgAgentVfsStore(vfs_pool)


@pytest.fixture()
def wire_session_dsn(wire_dev_env: dict[str, str]) -> str:
    dsn = _wire_dev_session_dsn(wire_dev_env)
    if not dsn:
        pytest.skip("HERMES_SESSION_DSN unset — run (agents-runtime) ./scripts/wire-dev.sh env")
    return dsn


@pytest.fixture()
def wire_agent_name() -> str:
    """Unique VFS agent scope per test — avoids clobbering dev registrations."""
    suffix = uuid.uuid4().hex[:12]
    return f"hermes-wire-{suffix}"


@pytest.fixture()
async def cleanup_wire_agent(vfs_store, wire_agent_name: str):
    yield
    pattern = "/profile/**"
    try:
        paths = await vfs_store.glob(KIND, wire_agent_name, pattern)
        for path in paths:
            await vfs_store.delete(KIND, wire_agent_name, path)
    except Exception:
        pass
